spring.application.name=AI-SERVICE

server.port=8083

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Gemini API
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Model
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL}