spring.application.name=AUTH-SERVICE
server.port = 8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
eureka.client.service-url.defaultZone=${EUREKA_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.instance.prefer-ip-address=true
